### ISSUE TITLE
Prometheus plugin not shown for inCluster deployment

### ISSUE THREAD

**Issue by SquupS** [headlamp-k8s/headlamp#1800] opened 2024-03-13 15:17 UTC
I have build and shipped the prometheus plugin to the 0.23.0 inCluster Deployment of headlamp.

However, the plugin is not shown under settings/plugins, nor do I see the switch to turn it on.

The plugin folder is propperly placed in /headlamp/plugins/ which is also the source for the -plugin-dir flag.

Any hints what I have missed?

**Comment by joaquimrocha** [comment] 2024-03-15 10:39
@SquupS , Indeed that seems like a problem in reading the plugin from its source location. Are you passing the `main.js` + `package.json` file of that plugin, or just the `main.js`? Both are needed so Headlamp knows whether the plugin is compatible.
If you are passing both files, can you share more details about your Headlamp deployment?

@yolossn , can you follow up with @SquupS 's replies?
Maybe we should also update this post just with a quick note that the package.json needs to be included as well (no need to modify the whole post/screenshots, just an **Update:** notice where needed)
https://headlamp.dev/blog/2022/10/get-up-to-speed-deploying-headlamp-with-plugins/

**Comment by SquupS** [comment] 2024-03-15 11:01
@joaquimrocha @yolossn yes, both files are provided within the folder

![image](https://github.com/headlamp-k8s/headlamp/assets/86827605/d2aa78ee-00d2-4d15-b56d-7aadcd32124c)

Besides that, it is just a pretty default deployment with the following args and envs


          args:
            - '-in-cluster'
            - '-insecure-ssl'
            - '-base-url=/headlamp'
            - '-plugins-dir=/headlamp/plugins/'

          env:
            - name: HEADLAMP_CONFIG_BASE_URL
              value: /headlamp

**Comment by yolossn** [comment] 2024-03-15 12:34
@SquupS Can you share the response that you get when accessing `<YOUR-HEADLAMP-URL>/headlamp/plugins`?

**Comment by SquupS** [comment] 2024-03-15 12:40
Sure @yolossn 

[
    "/headlamp/static-plugins/prometheus",
    "/headlamp/plugins/headlamp-plugins"
]

**Comment by SquupS** [comment] 2024-03-15 13:36
There are some, yes @yolossn 

![image](https://github.com/headlamp-k8s/headlamp/assets/86827605/b843f049-af41-4075-9c39-91103f0e4883)

Is this static one some automatically added plugin? Because if this gets ship per default, I would not have added one manually :-) But also without adding the plugin unter /headlamp/plugins I got no prometheus button/charts shown

**Comment by SquupS** [comment] 2024-03-18 09:35
Sure I can redeploy @yolossn But I was already using the latest 0.23.0 Version.

**Comment by SquupS** [comment] 2024-03-18 10:45
@yolossn redeployed and removed my added plugin, so that only the static one is left. I receive the same errors like schown before and no button shown for metrics.

Are there maybe any uncommented preconditions in order for that button to appear? I also compared my helm Chart to the one you provide here and those are more or less identical

**Comment by yolossn** [comment] 2024-03-18 11:28
Thanks for the update, Can you expand the errors that you see in the console and share it?

**Comment by SquupS** [comment] 2024-03-18 15:28
@yolossn hope that suits your needs?

![image](https://github.com/headlamp-k8s/headlamp/assets/86827605/deba01f8-8079-41a1-ac4a-1df5900da6bb)

**Comment by yolossn** [comment] 2024-03-20 07:23
@SquupS After a couple of attempts I am able to reproduce this error. Apparently it is occurring due to the "-base-url" argument, It works properly when the `-base-url` argument isn't set. I will work on a fix for this.

**Comment by SquupS** [comment] 2024-03-20 08:12
@yolossn that sounds awesome. Looking foward to the fix. Thanks a lot for the investigation.

**Comment by yolossn** [comment] 2024-03-28 07:24
@SquupS Could you please test the custom container build with the fix I created and pushed to `ttl.sh/headlamp-base-path-fix:latest`? This is to verify if the solution resolves the issue with using the Prometheus plugin correctly. Thanks!

**Comment by SquupS** [comment] 2024-03-28 08:52
@yolossn Can confirm, that the metrics button is now showing up per default, without having to run an init container or such.

**Closed** 2024-03-30 12:05 UTC
Labels: plugins, in-cluster
