### ISSUE TITLE
Proposal: add handy buttons for deployments

### ISSUE THREAD

**Issue by razonyang** [headlamp-k8s/headlamp#1540] opened 2023-11-09 11:26 UTC
It would be helpful that if provides these buttons like OpenLens.

![image](https://github.com/headlamp-k8s/headlamp/assets/17720932/64d991d7-d2c2-4d6a-9b56-6da6ca1e41e6)

**Comment by joaquimrocha** [comment] 2023-11-09 13:49
@razonyang , yes, we have that in our plans!

**Comment by joaquimrocha** [comment] 2024-07-18 09:39
Duplicate of #1006

**Comment by skoeva** [comment] 2024-11-05 15:46
Fixed by #2044, closing this now

**Closed by skoeva** 2024-11-05 15:46 UTC
Labels: enhancement, frontend
